### ISSUE TITLE
allow to upload filter rules file

### ISSUE THREAD

**Issue by philcerf** [bbdoc/PoracleWeb#54]
Hey.

I've had a chat with @jfberry today, about multiple commands per telegram/discord message (which is not that easily possible).... and there was the idea that it would be a nice feature if one could upload a text file of commands through poracle-web.

I.e. for people with many/complex rules, which are perhaps created from scripts themselves... and where entering them via both poracle web or individual commands (one by one) is not feasible.

So the idea is that one presents a file like:
```
/track Bulbasaur iv100
/track Magikarp d200
...
```
perhaps also allowing discord syntax... and poracleweb would parse this and add it do the user's rules, or maybe even better: simply execute them as if they were commands, so that one could also place /start /stop in the files.

Users could then also add their own clean-up commands like /untrack everything in such files.

Cheers!

**Comment by bbdoc** [comment]
I don't think PoracleWeb is the right place for this... it's not using the command mechanism of Poracle at all and the main idea was to create an abstraction layer so that users don't have to remember all those commands for setting their alarms. I don't even explain my users that they can set trackings using commands, they only use PoracleWeb.

If this needs to be implemented it should be on Poracle side. Let people upload a file to the discord/telegram and let Poracle interpret it (which btw can already be done easily by simply copy-pasting it into the discord/telegram chat)

**Comment by jfberry** [comment]
That's not quite how the conversation went.
I came up with an idea of allowing split commands for pasting.

But, we discussed something that I think would work well in PoracleWeb - which would be a CSV download/upload.
I wasn't thinking of command processing but pretty much the monster table!

**Comment by bbdoc** [comment]
Which would pretty much be issue #46 

The whole idea behind PoracleWeb is to add an easy interface to edit your tracking... loading them with a csv file quite of defeat the purpose... apart from doing backup/restore indeed.
